Submission for homework 1
linh224/CS464P-FrontEnd pull request #1
Opened 2023-10-04 06:53 UTC by linh224

**Exercise 01 - CSS Selectors**
I added solutions to the game's 32 levels. 

**Exercise 02 - Palindrome**
1. Updated  palindrome.html
I used Bootstrap classes to style the HTML page. I added the background color, created a form element, and added style for label input. I also created id number and id result that help me on interaction and manipulation in JavaScript. 
2. Updated palindrome.js
- First, I get the input number with the id "number"
- Next, check if the element was found 
-  I also have reset function to clear any previous result
- Then I check if the input number is a palindrome or not
- I added an event listener for the "keyup" event

**Feed back on the code**
The color I put to the background differs from the sample. Should I make a.css file for this situation?

2023-10-04 22:59 UTC, hickamt requested changes
Please review some of the suggestions that I have made. The important point (at the last line of code) suggests that you re-write the program according to dynamic input.

You are currently requiring the user to hit 'ENTER' before validating the input. The input should be validated for each input value without hitting 'ENTER'.

2023-10-04 22:59 UTC, hickamt commented on hw1/02-palindrome.js
> +  // Check if the input is empty
For each of these 'if()' checks, you could abstract them to their own function calls. Doing this might allow you to see that a few of them could be more general functions allowing code reuse.

2023-10-04 22:59 UTC, hickamt commented on hw1/02-palindrome.js
> +/**
The two parts of this event listener could be handles as a single event:

```
numberInput.addEventListener("keyup", (event) => {
   if (numberInput && event.keyCode === 13) {
     palindrome();
   }
});
```

2023-10-04 22:59 UTC, hickamt commented on hw1/02-palindrome.js
> +}
NOTE: the instructor wants the code input to be validated in real time. You are requiring the user to hit 'ENTER' to validate the input. The Palindrome input should allow input and validation dynamically.

2023-10-04 22:59 UTC, hickamt commented on hw1/01-selectors.md
> +12. plate + apple
#16, I am not able to use your selector to pass this one.
you might try using
`plate apple:only-child, plusSomethingHere...`

2023-10-04 22:59 UTC, hickamt commented on hw1/01-selectors.md
> +32. [for*="obb"]
Great job, only #16 should be re-worked.

2023-10-04 23:08 UTC, hickamt commented on hw1/02-palindrome.js
> +  if (value === "") {
For each of these 'if()' checks, you could abstract them to their own function calls. Doing this might allow you to see that a few of them could be more general functions allowing code reuse.

2023-10-05 04:22 UTC, linh224 commented on hw1/01-selectors.md
> +12. plate + apple
Hi Todd,
I passed #16 by using _plate > :only-child_
I used plate > to choose all plates, and use :only-child to choose the plates that have one child 
I also tried your way, and it passed as well. 
Can you try that again :)

2023-10-06 07:16 UTC, linh224 commented on hw1/02-palindrome.js
> +  if (value === "") {
Hello, Todd.
 Because I only use each **if** once, I don't build them as functions, but I think your suggestion is great!
Thank you for your advice.

2023-10-06 07:18 UTC, linh224 commented on hw1/02-palindrome.js
> +}
Thank you for the reminder. I had not realized that code input needed to be checked in real time. :)

2023-10-06 07:20 UTC, linh224 commented on hw1/02-palindrome.js
> +/**
Thank you for your advice. It is, in my opinion, very good; it has helped my code become cleaner and easier to follow.

2023-10-07 04:04 UTC, JoshuaWachana reviewed
Hello Linh,

Good job getting this assignment done. You did a pretty good job. I have left a few comments and suggestions.

Have a good day!

2023-10-07 04:04 UTC, JoshuaWachana commented on hw1/02-palindrome.html
> +        </form>
Out of curiosity, why is this being implemented with an html form? Is using a form necessary?

2023-10-07 04:04 UTC, JoshuaWachana commented on hw1/02-palindrome.html
> +          onsubmit="return false;"
Using the onsubmit method in the html file goes against the separation of concerns. The html file should just contain the html markup, actions should be put in the javascript file.

2023-10-07 04:04 UTC, JoshuaWachana commented on hw1/02-palindrome.html
> +            <span>Is this a palindrome?</span>
Why does this use a span element? Unless you will be styling this particular line it may be more appropriate to just stick with the p element.

2023-10-07 04:04 UTC, JoshuaWachana commented on hw1/02-palindrome.js
> +      reset.style.color = "red";
The assignment instructions suggested using Boostrap to handle styling. For consistency, consider just adding the bootstap class for red, which is "text-danger".

2023-10-07 04:04 UTC, JoshuaWachana commented on hw1/02-palindrome.js
> +      reset.style.color = "red";
The assignment instructions suggested using Boostrap to handle styling. For consistency, consider just adding the bootstap class for red, which is "text-danger".

2023-10-07 04:04 UTC, JoshuaWachana commented on hw1/02-palindrome.js
> +        reset.style.color = "red";
The assignment instructions suggested using Boostrap to handle styling. For consistency, consider just adding the bootstap class for red, which is "text-danger".

2023-10-07 04:04 UTC, JoshuaWachana commented on hw1/02-palindrome.js
> +  reset.style.color = "green";
The assignment instructions suggested using Boostrap to handle styling. For consistency, consider just adding the bootstap class for red, which is "text-success".

2023-10-07 04:04 UTC, JoshuaWachana commented on hw1/02-palindrome.js
> +  for (let i = 0; i < len / 2; i++) {
The Airbnb styleguide rule [13.6](https://github.com/airbnb/javascript#variables--unary-increment-decrement) says to avoid using unary increments and decrements (++, --).

2023-10-08 05:01 UTC, linh224 commented on hw1/02-palindrome.html
> +        </form>
Hello Joshua,
At first, I thought this was a form because we needed to submit something. The code input had to be checked in real time, but I didn't realize it.  So I used an HTML form to implement it. Now, as for whether it is required, I believe it is not.  :(

2023-10-08 05:04 UTC, linh224 commented on hw1/02-palindrome.html
> +          onsubmit="return false;"
Hi Joshua,
Thank you for pointing out the error. This will be fixed.

2023-10-08 05:08 UTC, linh224 commented on hw1/02-palindrome.html
> +            <span>Is this a palindrome?</span>
Hi Joshua,
Excellent observation. In this situation, I overlooked the block and inline elements. I'll fix it with p. Thank you!

2023-10-08 05:13 UTC, linh224 commented on hw1/02-palindrome.js
> +      reset.style.color = "red";
Hi Joshua,
Thank you for your feedback. Because this is my first time using Bootstrap, I have numerous flaws. I will fix it.

2023-10-08 05:14 UTC, linh224 commented on hw1/02-palindrome.js
> +      reset.style.color = "red";
I will fix it. Thank you Joshua!

2023-10-08 05:14 UTC, linh224 commented on hw1/02-palindrome.js
> +        reset.style.color = "red";
I will fix it. Thank you Joshua!

2023-10-08 05:14 UTC, linh224 commented on hw1/02-palindrome.js
> +  reset.style.color = "green";
I will fix it. Thank you Joshua!

2023-10-08 05:30 UTC, linh224 commented on hw1/02-palindrome.js
> +  for (let i = 0; i < len / 2; i++) {
Hi Joshua,
Thank you so much for your feedback. I will fix it. :)

2023-10-18 18:23 UTC, merged